name = "ev-venture-league-simulation"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
NODE_ENV = "production"
APP_TITLE = "EV Venture League Simulation"

[[d1_databases]]
binding = "DB"
database_name = "strategy-sim-db"
database_id = "41cead96-9092-4981-ad43-393fafa53a25"
migrations_dir = "d1/migrations"
